/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testdbihm;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jason
 */
public class FenetreEtudiant extends javax.swing.JFrame {

    /**
     * Creates new form FenetreEtudiant
     */
    public FenetreEtudiant() {
        initComponents();
chargerDonneesDansTable();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TMatricule = new javax.swing.JTextField();
        TNom = new javax.swing.JTextField();
        TAge = new javax.swing.JTextField();
        jComboBoxClasse = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BAnnuler = new javax.swing.JButton();
        BAjouter = new javax.swing.JButton();
        BModifier = new javax.swing.JButton();
        BSupprimer = new javax.swing.JButton();
        BAfficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jPanel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 3, 14)); // NOI18N
        jLabel2.setText("Nom Complet");

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 3, 14)); // NOI18N
        jLabel3.setText("Matricule");

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 3, 14)); // NOI18N
        jLabel5.setText("Age");

        jLabel6.setFont(new java.awt.Font("Cascadia Mono", 3, 14)); // NOI18N
        jLabel6.setText("Classe");

        TMatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TMatriculeActionPerformed(evt);
            }
        });

        TNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNomActionPerformed(evt);
            }
        });

        TAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAgeActionPerformed(evt);
            }
        });

        jComboBoxClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPAM 1", "TIPAM 2", "CS2I", "GL" }));
        jComboBoxClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClasseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TMatricule)
                    .addComponent(TNom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TAge, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 265, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricule", "Nom", "Age", "Classe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Matricule");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Nom");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Age");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Classe");
        }

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des etudiants");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(347, 347, 347))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        BAnnuler.setFont(new java.awt.Font("Cascadia Mono", 3, 12)); // NOI18N
        BAnnuler.setText("Annuler");
        BAnnuler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });

        BAjouter.setFont(new java.awt.Font("Cascadia Mono", 3, 12)); // NOI18N
        BAjouter.setText("Ajouter");
        BAjouter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjouterActionPerformed(evt);
            }
        });

        BModifier.setFont(new java.awt.Font("Cascadia Mono", 3, 12)); // NOI18N
        BModifier.setText("Modifier");
        BModifier.setToolTipText("");
        BModifier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BModifier.setPreferredSize(null);
        BModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModifierActionPerformed(evt);
            }
        });

        BSupprimer.setFont(new java.awt.Font("Cascadia Mono", 3, 12)); // NOI18N
        BSupprimer.setText("Supprimer");
        BSupprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BSupprimer.setPreferredSize(new java.awt.Dimension(82, 22));
        BSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSupprimerActionPerformed(evt);
            }
        });

        BAfficher.setFont(new java.awt.Font("Cascadia Mono", 3, 12)); // NOI18N
        BAfficher.setText("Afficher");
        BAfficher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAfficherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(BAnnuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(89, 89, 89)
                        .addComponent(BAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(103, 103, 103)
                        .addComponent(BModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(BSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(95, 95, 95)
                        .addComponent(BAfficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BAnnuler)
                        .addComponent(BAjouter))
                    .addComponent(BModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BAfficher)
                        .addComponent(BSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  // Méthode pour charger les données dans le JTable
private void chargerDonneesDansTable() {
     try {
            //Charger le pilote
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdb", "root", "");
            
            String query = "select * from etudiant";
            PreparedStatement st = con.prepareStatement(query);
            ResultSet RS = st.executeQuery();
            DefaultTableModel tableModels = (DefaultTableModel) jTable1.getModel();
            tableModels.setRowCount(0);
            
            while (RS.next()) {
                String matricule = RS.getString("matricule");
                String nom = RS.getString("nom");
                
           
                int age = RS.getInt("age");
                     String classe = RS.getString("classe");
                tableModels.addRow(new Object[]{matricule, nom,age,classe});
            }
//            JOptionPane.showMessageDialog(null, "Afficher reussie");
            System.out.println("Afficher reussie");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Afficher  non effectuer" + e);
        }
}
    
    private void TMatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TMatriculeActionPerformed

    private void TNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNomActionPerformed

    private void TAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAgeActionPerformed

    private void BAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjouterActionPerformed
        try {
            //Charger le pilote
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdb", "root", "");

            String matricule = TMatricule.getText();
            String nom = TNom.getText();
           
            String StringAge = TAge.getText();
            int age = Integer.parseInt(StringAge);
            
            String classe = jComboBoxClasse.getSelectedItem().toString();
            PreparedStatement st = con.prepareStatement("insert into etudiant values (?,?,?,?)");
            st.setString(1, matricule);
            st.setString(2, nom);
            
            st.setInt(3, age);
                 st.setString(4,classe);
            
            st.executeUpdate();

            JOptionPane.showMessageDialog(null, "Insertion reussie");
            System.out.println("Insertion reussie");

            TMatricule.setText("");
            TNom.setText("");
           
            TAge.setText("");
            
chargerDonneesDansTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ajout non effectuer");
        }
    }//GEN-LAST:event_BAjouterActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        TMatricule.setText("");
        TNom.setText("");
        
        TAge.setText("");
        
    }//GEN-LAST:event_BAnnulerActionPerformed

    private void BModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModifierActionPerformed
        try {
            //Charger le pilote
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdb", "root", "");

            String matricule = TMatricule.getText();
            String nom = TNom.getText();
         
            String StringAge = TAge.getText();
            int age = Integer.parseInt(StringAge);
           String classe = jComboBoxClasse.getSelectedItem().toString();
            PreparedStatement st = con.prepareStatement("update etudiant set nom = ? , age = ? ,classe = ? where matricule = ? ");
 st.setString(4, matricule);
            st.setString(1, nom);
            
            st.setInt(2, age);
            st.setString(3, classe);
            st.setString(4, matricule);
            st.executeUpdate();
 TMatricule.setText("");
            TNom.setText("");
           
            TAge.setText("");
            JOptionPane.showMessageDialog(null, "Mise a jour reussie");
            System.out.println("Mise a jour reussie");
            chargerDonneesDansTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Mise a jour non effectuer");
        }
    }//GEN-LAST:event_BModifierActionPerformed

    private void BSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSupprimerActionPerformed
        try {
            //Charger le pilote
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdb", "root", "");

            String matricule = TMatricule.getText();

            PreparedStatement st = con.prepareStatement(" DELETE FROM etudiant WHERE matricule = ?");

            st.setString(1, matricule);
            st.executeUpdate();

            JOptionPane.showMessageDialog(null, "Suppresion reussie");
            System.out.println("Suppresion reussie");
            chargerDonneesDansTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Suppresion  non effectuer" + e);
        }
    }//GEN-LAST:event_BSupprimerActionPerformed

    private void BAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAfficherActionPerformed
        try {
            //Charger le pilote
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdb", "root", "");
            
            String query = "select * from etudiant";
            PreparedStatement st = con.prepareStatement(query);
            ResultSet RS = st.executeQuery();
            DefaultTableModel tableModels = (DefaultTableModel) jTable1.getModel();
            tableModels.setRowCount(0);
            
            while (RS.next()) {
                String matricule = RS.getString("matricule");
                String nom = RS.getString("nom");
                
           
                int age = RS.getInt("age");
                     String classe = RS.getString("classe");
                tableModels.addRow(new Object[]{matricule, nom,age,classe});
            }
//            JOptionPane.showMessageDialog(null, "Afficher reussie");
            System.out.println("Afficher reussie");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Afficher  non effectuer" + e);
        }
    }//GEN-LAST:event_BAfficherActionPerformed

    private void jComboBoxClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClasseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreEtudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAfficher;
    private javax.swing.JButton BAjouter;
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BModifier;
    private javax.swing.JButton BSupprimer;
    private javax.swing.JTextField TAge;
    private javax.swing.JTextField TMatricule;
    private javax.swing.JTextField TNom;
    private javax.swing.JComboBox<String> jComboBoxClasse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
